# Generated by Django 4.2.6 on 2023-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(default=None, max_length=100, null=True)),
                ('Answer', models.CharField(default=None, max_length=100, null=True)),
                ('Keywords', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Question_Answer',
            },
        ),
    ]
