# Generated by Django 4.2.6 on 2023-10-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0002_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_answer',
            name='Answer',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
