# Generated by Django 4.2.6 on 2023-10-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0003_alter_question_answer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyHospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(default=None, max_length=100)),
                ('Lat', models.CharField(default=None, max_length=100)),
                ('Lng', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'NearbyHospitals',
            },
        ),
    ]
