# Generated by Django 4.2.6 on 2023-10-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0004_nearbyhospitals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyhospitals',
            name='Lat',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='nearbyhospitals',
            name='Lng',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='nearbyhospitals',
            name='hospitalname',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
