# Generated by Django 4.2.6 on 2023-10-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0005_alter_nearbyhospitals_lat_alter_nearbyhospitals_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyhospitals',
            name='Lat',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='nearbyhospitals',
            name='Lng',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='nearbyhospitals',
            name='hospitalname',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
