# Generated by Django 4.2.6 on 2023-10-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0006_alter_nearbyhospitals_lat_alter_nearbyhospitals_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Lat',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Lng',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
