# Generated by Django 4.2.6 on 2023-10-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0007_userdetails_lat_userdetails_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_answer',
            name='Tag',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
